# Generated by Django 2.1.2 on 2019-01-30 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Detail',
            fields=[
                ('ISBN', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('publication_date', models.DateField(verbose_name='Date')),
                ('online', models.BooleanField()),
                ('no_of_copies_available_offline', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_from_date', models.DateField(verbose_name='Date')),
                ('borrowed_to_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('actual_return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liberary.Book_Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Category_Table',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language_Table',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf_Detail',
            fields=[
                ('floor', models.IntegerField()),
                ('shelf_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Detail',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('is_admin', models.BooleanField()),
                ('designation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=7)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('Electrical', 'Electrical'), ('IT', 'IT')], max_length=10)),
                ('semester', models.IntegerField()),
                ('contact_number', models.CharField(max_length=12)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='borrower_detail',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liberary.Staff_Detail'),
        ),
        migrations.AddField(
            model_name='borrower_detail',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book_detail',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liberary.Category_Table'),
        ),
        migrations.AddField(
            model_name='book_detail',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liberary.Language_Table'),
        ),
        migrations.AddField(
            model_name='book_detail',
            name='shelf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liberary.Shelf_Detail'),
        ),
        migrations.AlterUniqueTogether(
            name='borrower_detail',
            unique_together={('student_id', 'ISBN')},
        ),
    ]
