# Generated by Django 2.1.2 on 2019-01-30 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liberary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_detail',
            name='id',
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
