# Generated by Django 2.1.2 on 2019-01-30 17:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liberary', '0002_auto_20190130_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower_detail',
            old_name='student_id',
            new_name='User',
        ),
        migrations.AlterUniqueTogether(
            name='borrower_detail',
            unique_together={('User', 'ISBN')},
        ),
    ]
